#!/usr/bin/with-contenv bash
# shellcheck shell=bash

RECIPES_DIRECTORY="/recipes"
mkdir -p "$RECIPES_DIRECTORY"

if [ ! -d "$RECIPES_DIRECTORY/.cooklang" ]; then
  echo "The .cooklang folder does not exist, creating new collection..."
  ls -la "$RECIPES_DIRECTORY"
  /usr/local/bin/chef collection new "$RECIPES_DIRECTORY"
  echo "New collection created!"
fi

/usr/local/bin/chef collection set "$RECIPES_DIRECTORY"

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    lsiown -R abc:abc \
        /config
    lsiown abc:abc \
        "$RECIPES_DIRECTORY"
fi