#!/usr/bin/with-contenv bash
# shellcheck shell=bash

RECIPES_DIRECTORY="/recipes"
mkdir -p "$RECIPES_DIRECTORY"

if [ ! -d "$RECIPES_DIRECTORY/.cooklang" ]; then
    echo "The .cooklang folder does not exist, creating new collection..."
    # See https://github.com/Zheoni/cooklang-chef/discussions/56#discussioncomment-14718863
    # /usr/local/bin/chef collection new "$RECIPES_DIRECTORY"
    mkdir "$RECIPES_DIRECTORY/.cooklang"
    echo "New collection created!"
fi

/usr/local/bin/chef collection set "$RECIPES_DIRECTORY"

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    lsiown -R abc:abc \
        /config

    if [ -d "$RECIPES_DIRECTORY/.config" ]; then
        lsiown -R abc:abc \
            "$RECIPES_DIRECTORY/.config"
    fi
    lsiown -R abc:abc \
        "$RECIPES_DIRECTORY/.cooklang"
    lsiown abc:abc \
        "$RECIPES_DIRECTORY"
fi